server:
  port: 18081
spring:
  config:
    import: "optional:nacos:${spring.application.name}-${spring.profiles.active}"
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        namespace: cloud-project
        server-addr: 172.24.136.195:8848
        file-extension: yml
      discovery:
        group: DEFAULT_GROUP
        namespace: cloud-project
        server-addr: 172.24.136.195:8848
logging:
  level:
    root: info